/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import fft.GestorGrises;
import fft.NumeroComplejo;
import fft.filtrosDeFrecuencia.Butterworth;
import fft.filtrosDeFrecuencia.FiltroIdealPasaAltas;
import fft.filtrosDeFrecuencia.FiltroIdealPasaBajas;
import fft.filtrosDeFrecuencia.Gaussiano;
import herramientas.HerramientasImagen;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;

/**
 *
 * @author KOKE
 */
public class JInternalFrameFiltrado extends javax.swing.JInternalFrame implements ActionListener {

    /**
     * Creates new form JInternalFrameConvolucion
     */
    private JInternalFrameImagen filtro;
    int size;
    Image io;
    JFramePrincipal framePrincipal;
    Butterworth B = null;
    FiltroIdealPasaAltas PA = null;
    FiltroIdealPasaBajas PB = null;
    Gaussiano G = null;
    GestorGrises g;
    NumeroComplejo[][] Filtrodecidido = null;

    public JInternalFrameFiltrado(JFramePrincipal framePrincipal, Image io, int size, GestorGrises g) {
        initComponents();
        this.framePrincipal = framePrincipal;
        this.size = size;
        this.io = io;
        this.g = g;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        vistaPrevia = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        butterAltas = new javax.swing.JRadioButton();
        butterBajas = new javax.swing.JRadioButton();
        radioSlider = new javax.swing.JSlider();
        pasaAltas = new javax.swing.JRadioButton();
        pasaBajas = new javax.swing.JRadioButton();
        gaussiano = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ordenTextF = new javax.swing.JTextField();
        gaussianoInverso = new javax.swing.JRadioButton();
        aplicarFiltro = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Crear Filtro");
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(250, 400));
        setPreferredSize(new java.awt.Dimension(566, 350));
        setVisible(true);

        vistaPrevia.setText("Previzualizar filtro");
        vistaPrevia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vistaPreviaActionPerformed(evt);
            }
        });

        butterAltas.setText("Butterworth(Altas)");
        butterAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butterAltasActionPerformed(evt);
            }
        });

        butterBajas.setText("Butterworth(Bajas)");
        butterBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butterBajasActionPerformed(evt);
            }
        });

        radioSlider.setMajorTickSpacing(20);
        radioSlider.setMaximum(255);
        radioSlider.setMinorTickSpacing(1);
        radioSlider.setPaintLabels(true);
        radioSlider.setPaintTicks(true);
        radioSlider.setSnapToTicks(true);
        radioSlider.setToolTipText("");
        radioSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        radioSlider.setValueIsAdjusting(true);

        pasaAltas.setText("Pasa Altas");
        pasaAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasaAltasActionPerformed(evt);
            }
        });

        pasaBajas.setText("Pasa Bajas");
        pasaBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasaBajasActionPerformed(evt);
            }
        });

        gaussiano.setText("Gaussiano");
        gaussiano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaussianoActionPerformed(evt);
            }
        });

        jLabel1.setText("Radio");

        jLabel2.setText("Orden");

        ordenTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenTextFActionPerformed(evt);
            }
        });

        gaussianoInverso.setText("Gaussiano(Inv)");
        gaussianoInverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaussianoInversoActionPerformed(evt);
            }
        });

        aplicarFiltro.setText("Aplicar filtro");
        aplicarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(vistaPrevia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aplicarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(radioSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pasaAltas)
                                    .addComponent(gaussiano)
                                    .addComponent(butterAltas))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gaussianoInverso)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(butterBajas)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ordenTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pasaBajas)))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butterAltas)
                    .addComponent(jLabel2)
                    .addComponent(ordenTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butterBajas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pasaAltas)
                    .addComponent(pasaBajas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gaussiano)
                    .addComponent(gaussianoInverso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aplicarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vistaPrevia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butterAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butterAltasActionPerformed
        this.pasaAltas.setSelected(false);
        this.pasaBajas.setSelected(false);
        this.butterBajas.setSelected(false);
        this.gaussiano.setSelected(false);
        this.gaussianoInverso.setSelected(false);
        this.ordenTextF.setEnabled(true);    }//GEN-LAST:event_butterAltasActionPerformed

    private void butterBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butterBajasActionPerformed
        this.pasaAltas.setSelected(false);
        this.pasaBajas.setSelected(false);
        this.butterAltas.setSelected(false);
        this.gaussiano.setSelected(false);
        this.gaussianoInverso.setSelected(false);
        this.ordenTextF.setEnabled(true);

    }//GEN-LAST:event_butterBajasActionPerformed

    private void pasaAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasaAltasActionPerformed
        this.butterBajas.setSelected(false);
        this.pasaBajas.setSelected(false);
        this.butterAltas.setSelected(false);
        this.gaussiano.setSelected(false);
        this.gaussianoInverso.setSelected(false);
        this.ordenTextF.setEnabled(false);
    }//GEN-LAST:event_pasaAltasActionPerformed

    private void pasaBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasaBajasActionPerformed
        this.butterBajas.setSelected(false);
        this.pasaAltas.setSelected(false);
        this.butterAltas.setSelected(false);
        this.gaussiano.setSelected(false);
        this.gaussianoInverso.setSelected(false);
        this.ordenTextF.setEnabled(false);    }//GEN-LAST:event_pasaBajasActionPerformed

    private void gaussianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaussianoActionPerformed
        this.butterBajas.setSelected(false);
        this.pasaBajas.setSelected(false);
        this.butterAltas.setSelected(false);
        this.pasaAltas.setSelected(false);
        this.gaussianoInverso.setSelected(false);
        this.ordenTextF.setEnabled(false);    }//GEN-LAST:event_gaussianoActionPerformed

    private void ordenTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordenTextFActionPerformed

    private void gaussianoInversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaussianoInversoActionPerformed
        this.butterBajas.setSelected(false);
        this.pasaBajas.setSelected(false);
        this.butterAltas.setSelected(false);
        this.gaussiano.setSelected(false);
        this.pasaAltas.setSelected(false);
        this.ordenTextF.setEnabled(false);    }//GEN-LAST:event_gaussianoInversoActionPerformed

    private void vistaPreviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vistaPreviaActionPerformed

        if (butterAltas.isSelected()) {

            B = new Butterworth(this.radioSlider.getValue(), new Dimension(this.size, this.size), true, Integer.parseInt(this.ordenTextF.getText()));
            B.crearFiltro();
            this.filtro = new JInternalFrameImagen(B.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = B.getFiltroEspacial();
        } else if (butterBajas.isSelected()) {

            B = new Butterworth(this.radioSlider.getValue(), new Dimension(this.size, this.size), false, Integer.parseInt(this.ordenTextF.getText()));
            B.crearFiltro();
            this.filtro = new JInternalFrameImagen(B.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = B.getFiltroEspacial();
        } else if (this.pasaAltas.isSelected()) {

            PA = new FiltroIdealPasaAltas(this.radioSlider.getValue(), new Dimension(this.size, this.size));
            PA.crearFiltro();
            this.filtro = new JInternalFrameImagen(PA.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = PA.getFiltroEspacial();
        } else if (this.pasaBajas.isSelected()) {

            PB = new FiltroIdealPasaBajas(this.radioSlider.getValue(), new Dimension(this.size, this.size));
            PB.crearFiltro();
            this.filtro = new JInternalFrameImagen(PB.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = PB.getFiltroEspacial();
        } else if (this.gaussiano.isSelected()) {

            G = new Gaussiano(this.radioSlider.getValue(), false, new Dimension(this.size, this.size));
            G.crearFiltro();
            this.filtro = new JInternalFrameImagen(G.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = G.getFiltroEspacial();
        } else if (this.gaussianoInverso.isSelected()) {

            G = new Gaussiano(this.radioSlider.getValue(), true, new Dimension(this.size, this.size));
            G.crearFiltro();
            this.filtro = new JInternalFrameImagen(G.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = G.getFiltroEspacial();
        }


    }//GEN-LAST:event_vistaPreviaActionPerformed

    private void aplicarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarFiltroActionPerformed
        if (butterAltas.isSelected()) {

            B = new Butterworth(this.radioSlider.getValue(), new Dimension(this.size, this.size), true, Integer.parseInt(this.ordenTextF.getText()));
            B.crearFiltro();
//            this.filtro = new JInternalFrameImagen(B.getImagen());
//            //filtro.setVisible(true);
//            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = B.getFiltroEspacial();
        } else if (butterBajas.isSelected()) {

            B = new Butterworth(this.radioSlider.getValue(), new Dimension(this.size, this.size), false, Integer.parseInt(this.ordenTextF.getText()));
            B.crearFiltro();
//            this.filtro = new JInternalFrameImagen(B.getImagen());
//            //filtro.setVisible(true);
//            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = B.getFiltroEspacial();
        } else if (this.pasaAltas.isSelected()) {

            PA = new FiltroIdealPasaAltas(this.radioSlider.getValue(), new Dimension(this.size, this.size));
            PA.crearFiltro();
//            this.filtro = new JInternalFrameImagen(PA.getImagen());
//            //filtro.setVisible(true);
//            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = PA.getFiltroEspacial();
        } else if (this.pasaBajas.isSelected()) {

            PB = new FiltroIdealPasaBajas(this.radioSlider.getValue(), new Dimension(this.size, this.size));
            PB.crearFiltro();
//            this.filtro = new JInternalFrameImagen(PB.getImagen());
//            //filtro.setVisible(true);
//            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = PB.getFiltroEspacial();
        } else if (this.gaussiano.isSelected()) {

            G = new Gaussiano(this.radioSlider.getValue(), false, new Dimension(this.size, this.size));
            G.crearFiltro();
//            this.filtro = new JInternalFrameImagen(G.getImagen());
//            //filtro.setVisible(true);
//            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = G.getFiltroEspacial();
        } else if (this.gaussianoInverso.isSelected()) {

            G = new Gaussiano(this.radioSlider.getValue(), true, new Dimension(this.size, this.size));
            G.crearFiltro();
//            this.filtro = new JInternalFrameImagen(G.getImagen());
//            //filtro.setVisible(true);
//            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = G.getFiltroEspacial();
        }

        BufferedImage bi = HerramientasImagen.toBufferedImage(io);

        BufferedImage bnuevo = new BufferedImage(bi.getWidth(), bi.getHeight(), BufferedImage.TYPE_INT_RGB);
        g = new GestorGrises(bi);
        this.g.obtenerImagenFrecuencias(true);
        this.g.aplicarFiltro(this.Filtrodecidido);
        bnuevo = g.obtenerImagenEspacial();

        JInternalFrameImagen internalNuevo23 = new JInternalFrameImagen(bnuevo);
        internalNuevo23.setVisible(true);
        this.framePrincipal.getjDesktopPanePrincipal().add(internalNuevo23);

    }//GEN-LAST:event_aplicarFiltroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplicarFiltro;
    private javax.swing.JRadioButton butterAltas;
    private javax.swing.JRadioButton butterBajas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton gaussiano;
    private javax.swing.JRadioButton gaussianoInverso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField ordenTextF;
    private javax.swing.JRadioButton pasaAltas;
    private javax.swing.JRadioButton pasaBajas;
    private javax.swing.JSlider radioSlider;
    private javax.swing.JButton vistaPrevia;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
