/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import fft.Gestor;
import fft.GestorGrises;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author koke
 */
public class JInternalFrameFrecuenciasFTT extends javax.swing.JInternalFrame implements ActionListener {

    /**
     * Creates new form JInternalFrameFrecuencias
     */
    Image imagen;
    JInternalFrameImagen internal;
    JFramePrincipal princial;

    public JInternalFrameFrecuenciasFTT(Image imagen, JInternalFrameImagen internal, JFramePrincipal principal) {
        initComponents();
        this.imagen = imagen;
        this.internal = internal;
        this.princial = principal;
        this.FTT.addActionListener(this);
        this.FTTinversa.addActionListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipos = new javax.swing.ButtonGroup();
        reajusteCuadrante = new javax.swing.JToggleButton();
        color = new javax.swing.JRadioButton();
        gris = new javax.swing.JRadioButton();
        FTT = new javax.swing.JButton();
        FTTinversa = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        reajusteCuadrante.setText("Re-ajustar cuadrante");

        tipos.add(color);
        color.setText("Color");
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        tipos.add(gris);
        gris.setText("Gris");

        FTT.setText("FFT");

        FTTinversa.setText("FFT INVERSA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FTTinversa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FTT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(reajusteCuadrante)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(color)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gris)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FTT)
                    .addComponent(gris))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FTTinversa)
                    .addComponent(color))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reajusteCuadrante)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FTT;
    private javax.swing.JButton FTTinversa;
    private javax.swing.JRadioButton color;
    private javax.swing.JRadioButton gris;
    private javax.swing.JToggleButton reajusteCuadrante;
    public static javax.swing.ButtonGroup tipos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        JInternalFrameImagen frameNuevo;
        Image imagenNueva = null;
        JButton boton = (JButton) e.getSource();
        GestorGrises gestorGrises = new GestorGrises(herramientas.HerramientasImagen.toBufferedImage(this.imagen));
        Gestor gestor = new Gestor(herramientas.HerramientasImagen.toBufferedImage(this.imagen));

        if (boton.getText().equals("FFT")) {
            if (this.gris.isSelected()) {
                imagenNueva = herramientas.HerramientasImagen.toImage(gestorGrises.obtenerImagenFrecuencias(this.reajusteCuadrante.isSelected()));
            } else if (this.color.isSelected()) {
                imagenNueva = herramientas.HerramientasImagen.toImage(gestor.obtenerImagenFrecuencias(this.reajusteCuadrante.isSelected()));
            }

            frameNuevo = new JInternalFrameImagen(imagenNueva);
            frameNuevo.setVisible(true);
            this.princial.getjDesktopPanePrincipal().add(frameNuevo);

        } else if (boton.getText().equals("FFT INVERSA")) {

            if (this.gris.isSelected()) {
                gestorGrises.obtenerImagenFrecuencias(this.reajusteCuadrante.isSelected());
                imagenNueva = herramientas.HerramientasImagen.toImage(gestorGrises.obtenerImagenEspacial());
            } else if (this.color.isSelected()) {
                gestor.obtenerImagenFrecuencias(this.reajusteCuadrante.isSelected());
                imagenNueva = herramientas.HerramientasImagen.toImage(gestor.obtenerImagenEspacial());
            }
            frameNuevo = new JInternalFrameImagen(imagenNueva);
            frameNuevo.setVisible(true);
            this.princial.getjDesktopPanePrincipal().add(frameNuevo);
        }

    }
}
